modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/SistrScarlet/LittleMaidModelLoader-Fabric/issues"
license = "https://github.com/SistrScarlet/LittleMaidModelLoader-Fabric/blob/1.16_Architectury/LICENCE.md"

[[mods]]
modId = "littlemaidrebirth"
version = "${version}"
displayName = "LittleMaid ReBirth"
authors = "Sistr"
description = "いろいろ手伝ってくれたりくれなかったりする、ちいさなメイドさんを追加するMOD"
logoFile = "icon.png"

[[dependencies.littlemaidrebirth]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.littlemaidrebirth]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.littlemaidrebirth]]
modId = "architectury"
mandatory = true
versionRange = "[1.31.61,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.littlemaidrebirth]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.14.64,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.littlemaidrebirth]]
modId = "littlemaidmodelloader"
mandatory = true
versionRange = "[2.5.0,)"
ordering = "AFTER"
side = "BOTH"