modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/SistrScarlet/LittleMaidModelLoader-Fabric/issues"
license = "https://github.com/SistrScarlet/LittleMaidModelLoader-Fabric/blob/1.16_Architectury/LICENCE.md"

[[mods]]
modId = "littlemaidrebirth"
version = "${version}"
displayName = "LittleMaid ReBirth"
authors = "Sistr"
description = "いろいろ手伝ってくれたりくれなかったりする、ちいさなメイドさんを追加するMOD"
logoFile = "icon.png"

[[dependencies.littlemaidrebirth]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.littlemaidrebirth]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.littlemaidrebirth]]
modId = "architectury"
mandatory = true
versionRange = "[5.5.18,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.littlemaidrebirth]]
modId = "cloth_config"
mandatory = true
versionRange = "[7.0.69,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.littlemaidrebirth]]
modId = "littlemaidmodelloader"
mandatory = true
versionRange = "[5.0.0,)"
ordering = "AFTER"
side = "BOTH"