org.gradle.jvmargs=-Xmx3072M

minecraft_version=1.21.1
yarn_version=1.21.1+build.3
enabled_platforms=fabric,neoforge

archives_base_name=LMRB
mod_version=9.0.0-beta.1
maven_group=net.sistr.littlemaidrebirth

architectury_version=13.0.8

fabric_loader_version=0.16.10
fabric_api_version=0.116.4+1.21.1

neoforge_version=21.1.233
yarn_mappings_patch_neoforge_version=1.21+build.6

mod_menu_version=11.0.4
cloth_config_version=15.0.140
gjf_version=1.17.0
checkstyle_version=10.21.4
spotless_version=6.25.0
spotbugs_version=6.1.7
junit_version=5.10.2
junit_platform_version=1.10.2
